<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>WinSweep</AssemblyName>
    <StartupObject>WinSweepLauncher.Program</StartupObject>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <InvariantGlobalization>false</InvariantGlobalization>
    <ApplicationIcon>assets\winsweep.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(PortableBuild)' == 'true'">
    <DefineConstants>$(DefineConstants);PORTABLE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="WinSweepPayload.zip" LogicalName="WinSweepPayload.zip" />
  </ItemGroup>
</Project>
